### PR TITLE
LPS-76812 Links in email notifications coming from Forms are pointing to localhost

### PR DESCRIPTION
**Pull request by IstvanD**
Hello @natocesarrego 

Could you please review this pull request?

I switched the method `_portal.getControlPanelFullURL()` to `_portal.getSiteAdminURL()` so the URL will be constructed based on ThemeDisplay's data on the current URL.

Thank you and best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:test

**Comment by natocesarrego** [comment]
Hi @IstvanD,

I was taking a look on https://github.com/natocesarrego/liferay-portal/pull/106 and I've realized that your solution modifies code from a subrepo and the central repo, hence you'll need to split your solution in two different pulls. Therefore, please send one pull to the DDM subrepo with the modifications related to DDM and another pull to the central repo with the updates associated to DDL.

Thanks in advance.

**Comment by IstvanD** [comment]
Hi @natocesarrego 

I have sent the DDM changes to subrepo https://github.com/natocesarrego/com-liferay-dynamic-data-mapping/pull/5

However, the DDL Form Web module has been removed from master 3 days ago via https://issues.liferay.com/browse/LPS-76591

So the changes in DDL are no longer needed.

Best regards,
István

**Comment by natocesarrego** [comment]
Thanks, @IstvanD!

> However, the DDL Form Web module has been removed from master 3 days ago via https://issues.liferay.com/browse/LPS-76591

The guys were migrating the Form Portlet to the DDM subrepo, due this it was removed from the central.

**Pull request closed without merging**
